sudo: required
dist: trusty
language: node_js
cache: yarn
node_js:
- '7.1.0'
services:
- docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn test

#after_success:
#  - yarn coveralls

before_deploy:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # install aws cli
  - sudo apt-get -y install python-pip
  - pip install awscli
  - aws --version
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
